### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by NaufalF22** [Jorixon/JASM#117]
Somehow when i scroll character screen the app just crash and when i try open it again the app only display this
![gambar](https://github.com/Jorixon/JASM/assets/63091744/e84b244a-b216-4774-a0ee-a336f717ed7d)

log(?)

System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at GIMI_ModManager.WinUI.Services.ActivationService.CheckIfAlreadyRunningAsync()
   at GIMI_ModManager.WinUI.Services.ActivationService.ActivateAsync(Object activationArgs)
   at GIMI_ModManager.WinUI.App.OnLaunched(LaunchActivatedEventArgs args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

**Comment by Jorixon** [comment]
Hi,
This error happens when JASM checks if there is another instance running, however, this happens at the start of the program before even the main window is shown. But I'll add potential fix in the next release

**Comment by Jorixon** [comment]
@NaufalF22 Hi again, if you'd like then you try the new release to see if the problem is resolved

**Comment by NaufalF22** [comment]
> @NaufalF22 Hi again, if you'd like then you try the new release to see if the problem is resolved

Its resolve itself when i unzip old build
