### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by NaufalF22** [Jorixon/JASM#121]
Somehow i get this error when loading game
![gambar](https://github.com/Jorixon/JASM/assets/63091744/321673e6-40e2-44ee-95a9-c20aae2cc40c)

log? 
System.NullReferenceException: Object reference not set to an instance of an object.
   at GIMI_ModManager.WinUI.Views.ModUpdateAvailableWindow.<.ctor>b__2_0(FrameworkElement _, Object _)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

**Comment by NaufalF22** [comment]
![gambar](https://github.com/Jorixon/JASM/assets/63091744/f2dddf40-f4fe-4336-b4d9-22bec8f3137d)
New bug but so little log this time
Log(?) System.NullReferenceException: Object reference not set to an instance of an object.
