### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by AyakaLoyalist** [Jorixon/JASM#123]
System.Runtime.InteropServices.COMException (0x80004005)
   at GIMI_ModManager.WinUI.Services.BaseProcessManager`1.PickProcessPathAsync(Window windowHandle)
   at GIMI_ModManager.WinUI.ViewModels.CharactersViewModel.StartGenshinAsync()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

**Comment by Jorixon** [comment]
Hi,

COMExceptions are usually quite hard to debug. They are usually errors that occur due to some factor outside of JASM.

But I'll try to add a fix in the next release

**Comment by Bowen9292** [comment]
System.Runtime.InteropServices.COMException (0x80004005)
   at GIMI_ModManager.WinUI.ViewModels.SubVms.PathPicker.BrowseFolderPathAsync(WindowEx window) in D:\a\JASM\JASM\src\GIMI-ModManager.WinUI\ViewModels\SubVms\PathPicker.cs:line 91
   at GIMI_ModManager.WinUI.ViewModels.StartupViewModel.BrowseGimiModFolderAsync() in D:\a\JASM\JASM\src\GIMI-ModManager.WinUI\ViewModels\StartupViewModel.cs:line 159
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
