### ISSUE TITLE
Error when opening mod updater

### ISSUE THREAD

**Issue by Brejelinha** [Jorixon/JASM#127]
When JASM finds a mod update and i click the button to see available updates, the new screen opens but as soon as it loads the program crashes and says
`System.InvalidCastException: Specified cast is not valid.`
Im using JASM V2.12.2 on a recently installed Tiny11 OS<br><br><br>
Full logs from opening to crash (yes my system is set to portuguese)
```
[2024-02-03T01:26:55 INF ] Current culture: pt-br
[2024-02-03T01:26:55 INF ActivationService] JASM starting up in RELEASE mode...
[2024-02-03T01:26:57 WRN ] Image for others_objects not found at file:///C:/Users/phsil/Downloads/JASM/Assets/Games/Genshin/Images/objects/Object_Others.png
[2024-02-03T01:26:59 INF ModUpdateAvailableChecker] Checking for mod updates...
[2024-02-03T01:26:59 INF NotificationManager] Title: Finished checking for mod updates | Body: Finished checking for mod updates
[2024-02-03T01:28:40 FTL ] Unhandled exception
System.InvalidCastException: Não há suporte para esta interface

Não há suporte para esta interface

   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.Web.WebView2.Core.ICoreWebView2_13Methods.get_Profile(IObjectReference _obj)
   at Microsoft.Web.WebView2.Core.CoreWebView2.get_Profile()
   at GIMI_ModManager.WinUI.Views.ModUpdateAvailableWindow.<.ctor>b__2_0(FrameworkElement _, Object _)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

**Comment by Jorixon** [comment]
Hi, sorry for late response

If you're still using JASM, you can try and download this version here:
https://github.com/Jorixon/JASM/actions/runs/8238196852?pr=135
Scroll down to the bottom and there should be zip file to download. This is built the same way as all other releases.
![image](https://github.com/Jorixon/JASM/assets/143650598/780cbd43-2e9b-4206-a285-d88ec2f7aaf3)
It's a bit hard for me to test this but now it tries to do check before loading the in-App browser.

**Comment by Brejelinha** [comment]
Hi! Thanks for looking into it, the build worked!
![image](https://github.com/Jorixon/JASM/assets/134317872/5b84f2ba-599d-42ae-9428-d4d652ce8a4c)
Not crashing anymore.
