### ISSUE TITLE
NullReference Exception

### ISSUE THREAD

**Issue by elixxiry** [Jorixon/JASM#139]
**Describe the bug**
Got an exception thrown when clicking into a character's mods

**To Reproduce**
Can't seem to reproduce again. Tried clicking into same character (Kirara) as well as others & fiddling around with disabling/enabling mods.

**Screenshots**
![image](https://github.com/Jorixon/JASM/assets/51599768/3ddd413c-76f9-4c8c-a111-b0d993cf418a)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 23H2

**Additional context**
Not sure if worth submitting an issue for since it was the first it happened and I can't seem to get it to occur again, but hopefully it can help?

**Stack trace**
`System.NullReferenceException: Object reference not set to an instance of an object.
   at GIMI_ModManager.WinUI.ViewModels.SubVms.ModPaneVM.ReloadModSettings(CancellationToken cancellationToken)
   at GIMI_ModManager.WinUI.ViewModels.SubVms.ModPaneVM.LoadMod(ModModel modModel, CancellationToken cancellationToken)
   at GIMI_ModManager.WinUI.ViewModels.CharacterDetailsViewModel.OnModsSelected(Object sender, ModSelectedEventArgs args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()`

**Comment by Jorixon** [comment]
Thanks for the nug report :)

I've noticed this happening occasionally during development. I think I've found the issue that causes it, and this is hopefully fixed for the next release
