### ISSUE TITLE
"Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by rx-fly** [Jorixon/JASM#151]
Was installing a mod and clicking on it, and JASM had an apparent crash. Occured 3x, Lumine, Beidou, and Ningguang. Likely reproducible.

Settings were "Enable mod and disable others", "Show only characters with mods", Elevator Status not running, Mod auto update checker: stopped, game: genshin.

All three times I filled out the URL textbox, two of which where to GB.

occurred 2x in JASM v2.2, updated to v2.3 and occurred once so far, did not notice issue before.

Log:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at GIMI_ModManager.WinUI.ViewModels.SubVms.ModPaneVM.ReloadModSettings(CancellationToken cancellationToken)
   at GIMI_ModManager.WinUI.ViewModels.SubVms.ModPaneVM.LoadMod(ModModel modModel, CancellationToken cancellationToken)
   at GIMI_ModManager.WinUI.ViewModels.CharacterDetailsViewModel.OnModsSelected(Object sender, ModSelectedEventArgs args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()`

OS: Windows 10

No gameplay issues or cessation of gimi/3dmigoto noted at this time.

**Comment by EffortlessFury** [comment]
This happened to me a few times as well, but happened all very close together, and now not at all. Very curious.

**Comment by EffortlessFury** [comment]
It happened to me again. I'd clicked the new entry line quite quickly after adding it and that's when it crashed; I couldn't repro it doing the exact same steps, though, so perhaps there is a race condition somewhere. If so, that makes it harder to diagnose. 

Either way, my stack trace was identical, so at least you know where to look?

**Comment by Jorixon** [comment]
The logic for the ModPane is very finicky and the issue is indeed a race condition. Some part of the code is trying to load a mod into the pane while some other is trying to unload a mod. Don't want to just lock it either as it may cause UI freezes.

[v2.3.0](https://github.com/Jorixon/JASM/releases/tag/v2.3.0) Had a fix that at least fixed one of the causes. This happens quite rarely in my experience.
