### ISSUE TITLE
'0x00' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

### ISSUE THREAD

**Issue by its-x3non** [Jorixon/JASM#181]
**Describe the bug**
JASM Crashes after importing from character mod rar and backing out to character screen.

**To Reproduce**
1. Go to any character, in my case, I want to add a Lumine mod
2. Drag and drop mod, in my example, [this mod](https://gamebanana.com/mods/493086)
3. Add Mod (auto importing the GameBanana info results in same crash)
4. Back out to character screen
5. Crash
6. See error

**Stack Trace**
```
System.Text.Json.JsonException: '0x00' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '0x00' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at GIMI_ModManager.WinUI.Services.Notifications.ModNotificationManager.InitializeAsync()
   at GIMI_ModManager.WinUI.Services.Notifications.ModNotificationManager.InitializeAsync()
   at GIMI_ModManager.WinUI.Services.Notifications.ModNotificationManager.GetNotificationsForModAsync(Guid modId, NotificationType type)
   at GIMI_ModManager.WinUI.ViewModels.CharactersViewModel.RefreshNotificationsAsync()
   at GIMI_ModManager.WinUI.ViewModels.CharactersViewModel.OnNavigatedTo(Object parameter)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
   ```

**Inner Exception Stack Trace**
```
System.Text.Json.JsonReaderException: '0x00' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
```

**Expected behavior**
I expected to go back to the character mod screen without any problem or crash.

**Screenshots**
Here is an [imgur](https://imgur.com/a/YiVJCY1) for the gifs of my problem if I didn't explain it thoroughly.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - 21H2

**Additional context**
1. I'm able to access any other tab, but once I press the character mod tab, the program crashes (shown in crash instance 1)
2. The program also crashes if I try to drag and drop the folder inside of said character's mod folder (shown in crash instance 2)
3. The problem is gone once the mod is deleted (shown in crash instance 2)
4. Mods still work in-game, program just crashes when trying to open after importing

**Comment by Jorixon** [comment]
Hmmm,
A quick fix, if you don't mind wiping your JASM settings, is to delete the settings folder at: `%localAppData%\JASM`. If this does not fix it the problem is likely more fundamental. 

I'll see if I can add some error handling in the next release, so it at least doesn't crash the app.

**Comment by its-x3non** [comment]
This fix worked! Thank you so much.
I should have most likely submitted this earlier as it started happening when I updated from an older version to a newer version. I don't quite remember which version though as it was quite a while. I might have been updating from a v1.x version to a v2.x version.

Thank you again though, this has fixed my problem!
