### ISSUE TITLE
Exception during mod import

### ISSUE THREAD

**Issue by ElPresedente** [Jorixon/JASM#198]
**Describe the bug**

**To Reproduce**
1. Run program as administrator
2. Go to character page
3. Click on Mods
4. Click on Add mod/archive
5. See error

Exception:
System.Runtime.InteropServices.COMException (0x80004005)
   at GIMI_ModManager.WinUI.ViewModels.CharacterDetailsViewModel.AddModFolder()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

**Expected behavior**
Mod import dialog

**Screenshots**
![image](https://github.com/Jorixon/JASM/assets/60564136/01737c81-bff1-4bfc-8fbe-9175501de5c9)

**Desktop:**
 - OS: Windows 10
 - Version 22H2

Reprodusible at version 2.10.1

**Addditional info**
I'm using my custom launcher to run genshin, 3dmigoto and skin manager simultaniusly, so manager starts in elevated mode. If I launch JASM without elevation and elevate it directly from settings menu, import works fine

**Comment by Jorixon** [comment]
Interesting...

This seems to be an issue with the filePicker itself I belive it's outside of my control. Tried searching around a bit and can't find a quick solution for this.

Though I have been thinking about creating my own filePicker at some point
