### ISSUE TITLE
Browse error

### ISSUE THREAD

**Issue by Bowen9292** [Jorixon/JASM#248]
**Describe the bug**
Click on browse, then these is error come out.

**To Reproduce**
1. Go to 'JASM - Just Another Skin Manager'
2. Click on 'Browse'
3. See error

**Logs**
System.Runtime.InteropServices.COMException (0x80004005)
   at GIMI_ModManager.WinUI.ViewModels.SubVms.PathPicker.BrowseFolderPathAsync(WindowEx window) in D:\a\JASM\JASM\src\GIMI-ModManager.WinUI\ViewModels\SubVms\PathPicker.cs:line 91
   at GIMI_ModManager.WinUI.ViewModels.StartupViewModel.BrowseGimiModFolderAsync() in D:\a\JASM\JASM\src\GIMI-ModManager.WinUI\ViewModels\StartupViewModel.cs:line 159
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22h2

[Which version of Windows operating system am I running?](https://support.microsoft.com/en-us/windows/which-version-of-windows-operating-system-am-i-running-628bec99-476a-2c13-5296-9dd081cdd808)

**Additional context**

**Comment by Bowen9292** [comment]
I canceled adminnistrator run, I worked. No error. Maybe I do not check the pop-up notice.
