### ISSUE TITLE
unable to paste image when adding mod

### ISSUE THREAD

**Issue by Cooper8386** [Jorixon/JASM#249]
Error when trying to paste mod during drag and drop

1. drag an drop mod
2. copy image file
3. right click to paste image

mod would paste when adding mod instead of throwing error

https://i.imgur.com/l6ZAkCh.png

**Logs**
[2024-09-05T19:40:53 INF DragAndDropScanner] 7z extraction finished with exit code 0
[2024-09-05T19:41:17 ERR ] Failed retrieve image from clipboard
System.Runtime.InteropServices.COMException (0x8001010E)
   at GIMI_ModManager.WinUI.Services.ImageHandlerService.GetImageFromClipboardAsync() in D:\a\JASM\JASM\src\GIMI-ModManager.WinUI\Services\ImageHandlerService.cs:line 157
   at GIMI_ModManager.WinUI.ViewModels.ModInstallerVM.PasteModImageAsync() in D:\a\JASM\JASM\src\GIMI-ModManager.WinUI\ViewModels\ModInstallerVM.cs:line 442
[2024-09-05T19:41:17 INF NotificationManager] Title: Failed retrieve image from clipboard | Body: 

 - OS: Windows 11
 - 23H2

**Comment by Pyrageis** [comment]
sounds like your copying the file rather than the image itself, the image itself being copied isnt the same as copying the file
or the other way around, haven't used the paste image before so not sure which one it uses
