### ISSUE TITLE
"An error has occured: XAML parsing failed."

### ISSUE THREAD

**Issue by LokeYourC3PH** [Jorixon/JASM#263]
**Describe the bug**
Started the program from the same folder it was installed in as usual.

**To Reproduce**
1. Start program
2. Crash

**Expected behavior**
No crash?

**Screenshots**
![image](https://github.com/user-attachments/assets/c317989b-0b2d-4d23-bbce-cc781700e4a3)

**Logs**

```
Microsoft.UI.Xaml.Markup.XamlParseException: XAML parsing failed.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.LoadComponent(IObjectReference _obj, Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at GIMI_ModManager.WinUI.Views.CharactersPage..ctor()
   at GIMI_ModManager.WinUI.GIMI_ModManager_WinUI_XamlTypeInfo.XamlTypeInfoProvider.Activate_141_CharactersPage()
   at ABI.Microsoft.UI.Xaml.Markup.IXamlType.Do_Abi_ActivateInstance_13(IntPtr thisPtr, IntPtr* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IFrameMethods.Navigate(IObjectReference _obj, Type sourcePageType, Object parameter)
   at GIMI_ModManager.WinUI.Services.NavigationService.NavigateTo(String pageKey, Object parameter, Boolean clearNavigation, NavigationTransitionInfo transitionInfo)
   at GIMI_ModManager.WinUI.Activation.FirstTimeStartupActivationHandler.HandleInternalAsync(LaunchActivatedEventArgs args)
   at GIMI_ModManager.WinUI.Activation.ActivationHandler`1.HandleAsync(Object args)
   at GIMI_ModManager.WinUI.Services.ActivationService.HandleActivationAsync(Object activationArgs)
   at GIMI_ModManager.WinUI.Services.ActivationService.ActivateAsync(Object activationArgs)
   at GIMI_ModManager.WinUI.App.OnLaunched(LaunchActivatedEventArgs args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise
 - Version 23H2

**Additional context**
I had 1:1 copy-pasted the folder as I copied it to my NAS before reinstalling Windows. I just pasted it back to where exactly it used to be after reinstalling Windows 11, was met with the setup screen where I should pick the 3DMigoto directory, then clicked "Save", and since then every time I open the program I get this fatal error.

**Comment by LokeYourC3PH** [comment]
Fixed by completely nuking the folder from orbit and creating a fresh one. Still, shouldn't probably occur.
