### ISSUE TITLE
Window not found (Parameter "window")

### ISSUE THREAD

**Issue by LucciGr543** [Jorixon/JASM#90]
Idk why but the program keeps sending this message, any idea how to fix it?

System.ArgumentException: Window not found. (Parameter 'window')
   at GIMI_ModManager.WinUI.Services.AppManagment.WindowManagerService.GetWindow(WindowEx window)
   at GIMI_ModManager.WinUI.Services.AppManagment.WindowManagerService.ResizeWindowPercent(WindowEx window, Int32 widthPercent, Int32 heightPercent)
   at GIMI_ModManager.WinUI.ViewModels.StartupViewModel.OnNavigatedTo(Object parameter)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

**Comment by Jonathanio123** [comment]
Thanks for notifying me, getting a fix out right now

**Comment by Jorixon** [comment]
Thanks for notifying me, getting a fix out now

**Comment by Jorixon** [comment]
Fix is out with v1.8.1
